# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Chekout # step1 获取源码
      uses: actions/checkout@main # 使用 actions/checkout@v2
      with:
          persist-credentials: false

    - name: Cache node modules # step2
      uses: actions/cache@main # 使用 actions/cache@v1
      id: cache
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install Dependencies # step3 name
      if: steps.cache.outputs.cache-hit != 'true' # 如果变量 cache-hit 不等于 true
      run: npm install # 安装 node modules 相关依赖

    - name: Build
      run: npm run build
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@main
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: https://registry.npmjs.org

    - name: Publish
      run: npm publish .
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
